[project]
name = "unipr-clt-fisica"
version = "0.1.0"
description = "Add a short description here"
authors = ["RBerga06 <78449715+RBerga06@users.noreply.github.com>"]
channels = ["conda-forge", "https://repo.prefix.dev/rberga06/"]
platforms = ["osx-64"]

[tasks]

[dependencies]
python = ">=3.12"
numpy = ">=2.0.0,<2.1"
sympy = ">=1.12.1,<1.13"
pandas = ">=2.2.2,<2.3"
matplotlib = ">=3.9.1,<3.10"
ipywidgets = ">=8.1.3,<8.2"
ipykernel = ">=6.29.5,<6.30"
ipympl = ">=0.9.4,<0.10"
rberga06-phylab = ">=0.0.1.dev0,<0.0.2"

[pypi-dependencies]
useful-types = "*"
