name: "CI: LaTeX compilation"
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Compile r4-random
      #   uses: dante-ev/latex-action@latest
      #   with:
      #     root_file: relazione.tex
      #     working_directory: lab1/r4-random
      #     compiler: latexmk
      #     args: -interaction=nonstopmode -shell-escape -file-line-error -pdf -outdir=.
      # - name: Compile r5-torsione
      #   uses: dante-ev/latex-action@latest
      #   with:
      #     root_file: lab1/r5-torsione/relazione.tex
      #     compiler: latexmk
      #     args: -interaction=nonstopmode -shell-escape -file-line-error -pdf -outdir=lab1/r5-torsione/
      # - name: Compile r6-calorimetro
      #   uses: dante-ev/latex-action@latest
      #   with:
      #     root_file: lab1/r6-calorimetro/relazione.tex
      #     compiler: latexmk
      #     args: -interaction=nonstopmode -shell-escape -file-line-error -pdf -outdir=lab1/r6-calorimetro/
      - name: Compile r7-pendulum
        uses: dante-ev/latex-action@latest
        with:
          root_file: lab1/r7-pendulum/relazione.tex
          compiler: latexmk
          args: -interaction=nonstopmode -shell-escape -file-line-error -pdf -outdir=lab1/r7-pendulum/
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "CI: Compile LaTeX files to PDFs"
          git push
