name: "CI: LaTeX compilation"
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile r12-sound
        uses: dante-ev/latex-action@latest
        with:
          root_file: lab1/r12-sound/relazione.tex
          compiler: latexmk
          args: -interaction=nonstopmode -shell-escape -file-line-error -pdf -outdir=lab1/r12-sound/
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "CI: Compile LaTeX files to PDFs"
          git push
